### ISSUE TITLE
Support json-like format to print Message object

### ISSUE THREAD

**Issue by yoki123** [crazyhatfish/ProtoPy#3]
When I print the `msg` object in Example , the result is
`<exampleproto.CMsgClientGamesPlayed instance at 0xxxxxxxx>`

And the `msg.__dict__` isn't friendly with embedded Message.
`{'token': 'TOKENTOKENTOKENTOKEN', 'games': [<exampleproto.Game instance at 0xxxxxxxxx>], 'game_port': 1337, 'game_ip_address': 287454020}`

I think the json-like/dict-like format is very helpful to debug decoding result, such as
`{'game_ip_address': 287454020, 'game_port': 1337, 'token': 'TOKENTOKENTOKENTOKEN', 'games': [{'game_id': 1234, 'game_name': 'blah', 'game_version': 0}]}`

**Comment by crazyhatfish** [comment]
Its funny, I needed a to_dict function a few days ago, just hadn't committed it. Thanks for the help though.

**Comment by crazyhatfish** [comment]
Woops, `to_dict` doesn't work.
